# Generated by Django 4.1.5 on 2023-01-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=13, unique=True)),
                ('Cantidad', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Descripcion',
                'verbose_name_plural': 'Descripciones',
                'ordering': ('Descripcion',),
            },
        ),
    ]
