# Generated by Django 4.1.5 on 2023-01-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinari', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinaria',
            options={'ordering': ('Descripcion',), 'verbose_name': 'Descripcion', 'verbose_name_plural': 'Descripcion'},
        ),
    ]
